variable "environment" {
  description = "Deployment environment"
  type        = string
}

variable "account_id" {
  description = "AWS account ID (used for globally unique S3 bucket names)"
  type        = string
}

variable "private_subnet_ids" {
  description = "List of private subnet IDs from the network module"
  type        = list(string)
}

variable "rds_sg_id" {
  description = "Security group ID for RDS ingress"
  type        = string
}

variable "redis_sg_id" {
  description = "Security group ID for ElastiCache Redis ingress"
  type        = string
}

variable "db_password" {
  description = "RDS Postgres master password (generated by the secrets module)"
  type        = string
  sensitive   = true
}
